[build-system]
requires = ["uv_build>=0.10.0,<0.11.0"]
build-backend = "uv_build"

[project]
name = "DeOCR"
version = "0.3.2"
authors = [
    {name = "Moenupa", email = "moenupa@gmail.com"}
]
description = "A high-performance highly-customizable reverse OCR tool that renders text or huggingface-compatible datasets to images. Dimension, DPI, CSS configurable!"
readme = "README.md"
requires-python = ">=3.9,<3.15"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "jsonargparse[signatures]>=4.26.1",
    "datasets[vision]",
    "markdown-it-py>=3.0.0",
    "linkify-it-py",
]

[project.optional-dependencies]
playwright = [
    "playwright>=1.49.1,<1.59.0"
]
reportlab = [
    "reportlab>=4.4.4"
]
pymupdf = [
    "pymupdf",
]
ghactions = [
    "deocr[playwright,pymupdf]",
]

[dependency-groups]
dev = [
    "pre-commit",
    "pytest>=8.4.2",
    "pytest-asyncio",
    "pytest-xdist",
    "ruff",
    "build",
]

[project.urls]
homepage = "https://github.com/Moenupa/DeOCR"
source = "https://github.com/Moenupa/DeOCR"
issues = "https://github.com/Moenupa/DeOCR/issues"

[tool.pytest.ini_options]
addopts = "--ignore=tests/async/ -n 16"
markers = [
    "slow: mark tests as slow (pytest -m 'not slow' or set RUN_SLOW=1 to run)",
    "nocleanup: mark tests to skip cleanup fixture",
]
